apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments-service
  template:
    metadata:
      labels:
        app: appointments-service
    spec:
      containers:
      - name: appointments-service
        image: carelabs/carelabs-appointments-service:latest
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: shared-config
        - secretRef:
            name: shared-secret
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/carelabs_appointments"
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
