apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  # Placeholders for Service Discovery / Gateway URL
  EUREKA_URI: "http://discovery-server-service:8761/eureka"
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "rootpassword"
  JWT_SECRET: "your-512-bit-secret-key-goes-here"
