package com.carelabs.notificationservice.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.io.UnsupportedEncodingException;

/**
 * Low-level email sending service.
 * Wraps JavaMailSender and sends HTML-formatted emails.
 * All rendering logic lives in EmailTemplateService — this class only handles transport.
 */
@Service
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${app.mail.from}")
    private String fromAddress;

    @Value("${app.mail.from-name}")
    private String fromName;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    /**
     * Sends an HTML email.
     *
     * @param toEmail   recipient email address
     * @param subject   email subject line
     * @param htmlBody  full HTML content (generated by EmailTemplateService)
     * @throws MessagingException           if the email could not be sent
     * @throws UnsupportedEncodingException if the from-name encoding fails
     */
    public void sendHtmlEmail(String toEmail, String subject, String htmlBody)
            throws MessagingException, UnsupportedEncodingException {

        MimeMessage message = mailSender.createMimeMessage();

        // true = multipart (needed for HTML)
        MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

        helper.setFrom(fromAddress, fromName); // fromName causes UnsupportedEncodingException
        helper.setTo(toEmail);
        helper.setSubject(subject);
        helper.setText(htmlBody, true); // true = isHtml

        mailSender.send(message);
        log.info("Email sent successfully to {} | subject: {}", toEmail, subject);
    }
}