package com.carelabs.notificationservice.enums;

public enum NotificationEvent {
    APPOINTMENT_BOOKED,
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_REQUESTED,
    REFUND_PROCESSED,
    PRESCRIPTION_ISSUED,
    DOC_APPROVED,
    DOC_REJECTED,
    PAYOUT_PROCESSED,
    ANNOUNCEMENT
}